# Generated by Django 4.2.2 on 2023-06-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_groups_alter_account_user_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='account_images/'),
        ),
    ]
