# Generated by Django 4.1.7 on 2023-03-31 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(default='authors/default.jpg', upload_to='authors/'),
        ),
    ]
