# Generated by Django 4.1.7 on 2023-03-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.SmallIntegerField()),
                ('birth_data', models.DateField()),
                ('bio', models.TextField()),
            ],
        ),
    ]
