# Generated by Django 4.1.7 on 2023-04-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.URLField(default='https://via.placeholder.com/300x200'),
        ),
    ]
