# Generated by Django 4.1.7 on 2023-04-01 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='image',
            new_name='photo',
        ),
    ]
