# Generated by Django 4.1.7 on 2023-04-01 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_image_book_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='photo',
        ),
    ]
