# Generated by Django 4.1.7 on 2023-03-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('published', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('authors', models.ManyToManyField(to='authors.author')),
            ],
        ),
    ]
